# Generated by Django 4.1.7 on 2023-03-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("about", models.CharField(max_length=600)),
                ("address", models.CharField(max_length=1000)),
                (
                    "email",
                    models.CharField(default="undefined", max_length=50, unique=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=30, unique=True)),
                ("email", models.CharField(max_length=50, unique=True)),
                ("Phone", models.IntegerField()),
                ("address", models.CharField(max_length=200)),
                ("fullname", models.CharField(max_length=50)),
                ("pswrd", models.CharField(max_length=50)),
                ("iddetail", models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
